language: node_js
os: linux
dist: trusty
node_js:
  - 6
  
cache:
  directories:
    - node_modules
script:
  - npm run test
after_script: cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
