language: node_js
dist: trusty
node_js:
  - 6

cache:
  directories:
    - node_modules
after_script: NODE_ENV=test ./node_modules/istanbul/lib/cli.js cover ./node_modules/mocha/bin/_mocha -- -R spec -r jsdom-global/register ./test/*
